# Builds on all branches & PRs
# Deploys to PyPi on "release".
name: Build and publish

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the Python wheel
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Python wheels
        uses: RalfG/python-wheels-manylinux-build@v0.3.4-manylinux2010_x86_64
        with:
          python-versions: 'cp38-cp38 cp39-cp39 cp310-cp310'
          package-path: src
      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: src/dist/*.whl

  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    name: Deploy wheels to PyPI
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v2
        with:
          name: wheels
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          pip install twine
      - name: Publish wheels to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload *.whl
